config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
  path: 'auth', 
  path_names: {
     sign_in: 'login',
     sign_out: 'logout',
     password: 'secret',
     confirmation: 'verification',
     unlock: 'unblock',
     registration: 'register',
     sign_up: 'signup' 
    },
    controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "flights#index"
  get 'profiles', to: 'profiles#show', as: :show_profile
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
  resources :bookings, only: [:new, :create, :show]
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :route

  def departure_airport
    route&.airport_from
  end
  
  def arrival_airport
    route&.airport_to
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airports = Airport.all
    @flightdates = Flight.all.pluck(:departure_time)

    search_params = allow_search_flight_params

    if turbo_frame_request?
      flight_routes = Flight.joins(:route).where('Date(departure_time) = ?', params[:flight_date].to_date)
      flights = flight_routes.joins('JOIN airports ON airport_from_id = airports.id').where('code = ?', search_params[:departure_airport]) &
      flight_routes.joins('JOIN airports ON airport_to_id = airports.id').where('code = ?',search_params[:arrival_airport])
      num_tickets = search_params[:number_of_passengers]
      render partial: "flights/flight_frame", locals: {flights: flights, num_tickets: num_tickets }
    else
      render :index
    end

  end

  private
  def allow_search_flight_params
    params.permit(:departure_airport, :arrival_airport, :number_of_passengers, :flight_date, :commit)
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_flight.html.erb
<div class="card mb-3">
  <div class="card-body">
    <div class="d-flex">
      <div class="d-flex justify-content-center align-items-center pe-3">
        <%= form.radio_button :flight_id, flight.id, {class: "form-check-input ", type: "checkbox", style:"border-color: black"} %>
      </div>
      <%= render partial: "flight_data", locals: {flight: flight}%>
    </div>
  </div>

app/views/flights/_flight_data.html.erb
<div class="d-flex flex-grow-1">
  <div class="container-fluid">
    <div class="row mb-4">
      <div class="col-12 d-flex">
        <div>
          <%= "#{flight.departure_airport.name} (#{flight.departure_airport.code})"%>
        </div>
        <div class="flex-grow-1 text-center">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-airplane" viewBox="0 0 16 16" transform='rotate(90)'>
            <path d="M6.428 1.151C6.708.591 7.213 0 8 0s1.292.592 1.572 1.151C9.861 1.73 10 2.431 10 3v3.691l5.17 2.585a1.5 1.5 0 0 1 .83 1.342V12a.5.5 0 0 1-.582.493l-5.507-.918-.375 2.253 1.318 1.318A.5.5 0 0 1 10.5 16h-5a.5.5 0 0 1-.354-.854l1.319-1.318-.376-2.253-5.507.918A.5.5 0 0 1 0 12v-1.382a1.5 1.5 0 0 1 .83-1.342L6 6.691V3c0-.568.14-1.271.428-1.849Zm.894.448C7.111 2.02 7 2.569 7 3v4a.5.5 0 0 1-.276.447l-5.448 2.724a.5.5 0 0 0-.276.447v.792l5.418-.903a.5.5 0 0 1 .575.41l.5 3a.5.5 0 0 1-.14.437L6.708 15h2.586l-.647-.646a.5.5 0 0 1-.14-.436l.5-3a.5.5 0 0 1 .576-.411L15 11.41v-.792a.5.5 0 0 0-.276-.447L9.276 7.447A.5.5 0 0 1 9 7V3c0-.432-.11-.979-.322-1.401C8.458 1.159 8.213 1 8 1c-.213 0-.458.158-.678.599Z"/>
          </svg>
        </div>
        <div>
          <%= "#{flight.arrival_airport.name}  (#{flight.arrival_airport.code})"%>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md">
        <span><i class="bi bi-calendar-event"></i> Departure time:<br/>
          <%= flight.departure_time.localtime.strftime('%b %e, %Y at %l:%M %p (GMT%Z)') %>
        </div>
        <div class="col-md text-center">
          <span>Flight No.</span><br/>
          <%= flight.id %>
        </div>
        <div class="col-md text-end">
          <span><i class="bi bi-calendar-event"></i> Estimated arrival time:
            <br/>
            <%= (flight.departure_time + flight.route.duration*60).localtime.strftime('%b %e, %Y at %l:%M %p (GMT%Z)')%> </span>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/flights/_flight_frame.html.erb
<%= turbo_frame_tag "flight_frame" do  %>
  <div id="flight-data">
    <% if flights.nil? %>
      <p>Available flights will be listed here</p>
    <% elsif flights.empty? %>
      <p>No result</p>
    <% else %>
      <%= form_with url: new_booking_path, method: :get, data: {turbo_frame:"_top"} do |form| %>
        <% flights.each do |flight| %>
          <%= render partial: flight , locals: {form: form} %>
        <% end %>
        <div class="actions d-grid gap-2 col-12 mx-auto mb-4">
          <%= form.hidden_field :num_tickets, value: num_tickets %>
          <%= form.submit "Choose this flight", class: "btn btn-primary" %>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/flights/index.html.erb
<main>
  <div class="container mb-3">
    <div class="row">
      <div class="col-md-12">
        <h3 class="text-center mb-4">Search flights</h3>
        <%= form_with url: root_path, method: :get, data: {turbo_frame: "flight_frame"}  do |form| %>
          <div class="row g-4">
            <div class="col-md">
              <div class="field mb-4">
                <%= form.label :departure_airport, class: "form-label" %><br />
                <%= form.select :departure_airport, @airports.map {|airport| ["#{airport.code} (#{airport.name})", airport.code]}, {}, {class: "form-select"} %>
              </div>
            </div>
            <div class="col-md">
              <div class="field mb-4">
                <%= form.label :arrival_airport, class: "form-label" %><br />
                <%= form.select :arrival_airport,  @airports.map {|airport| ["#{airport.code} (#{airport.name})", airport.code]}, {}, {class: "form-select"} %>
              </div>
            </div>
            <div class="col-md">
              <div class="field mb-4">
                <%= form.label :number_of_passengers, class: "form-label" %><br />
                <%= form.select :number_of_passengers, [*1..4], {:selected => 1}, {class: "form-select"} %>
              </div>
            </div>
            <div class="col-md">
              <div class="field mb-4">
                <%= form.label :flight_date, class: "form-label" %><br />
                <%= form.date_field :flight_date, min: @flightdates.min.to_date, max: @flightdates.max.to_date, class:"form-control" %>
              </div>
            </div>
            <div class="col-md align-items-end">
              <%= form.label :search, class: "form-label text-white" %><br />
              <div class="actions d-grid gap-2 col-12 mx-auto mb-4">
                <%= form.submit "Search", class:"btn btn-primary d-md-block", onClick: "this.form.requestSubmit()" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row bg-light">
      <div class="col-md-12">
        <h3 class="text-center m-4">Available flights</h3>
        <div>
          <%= render partial: "flights/flight_frame", locals: {flights: nil, num_tickets: 0, loading: true } %>
          <div class="loading-ring spinner-border hidden" role="status">
            <span class="visually-hidden">Loading...</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>