config/routes.rb
Rails.application.routes.draw do
  devise_for :users, 
  path: 'auth', 
  path_names: {
     sign_in: 'login',
     sign_out: 'logout',
     password: 'secret',
     confirmation: 'verification',
     unlock: 'unblock',
     registration: 'register',
     sign_up: 'signup' 
    },
    controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "flights#index"
  get 'profiles', to: 'profiles#show', as: :show_profile
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'
  resources :bookings, only: [:new, :create, :show]
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm p-2 mb-3">
  <div class="container">
    <%= link_to "Odin Flight Booker", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= link_to current_user.username, root_path, class:"nav-link dropdown-toggle", role: "button", "data-bs-toggle" => "dropdown", "aria-expanded" => "false" %>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><%= link_to "Profile", show_profile_path(current_user.username), class:"dropdown-item"%></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= button_to 'Log out', destroy_user_session_path, class: 'dropdown-item', :method => :delete %></li>
            </ul>
          </li>
        <% else %>
          <% unless current_page?(new_user_session_path) || current_page?(new_user_registration_path)  %>
            <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary mx-2', type: 'button', data: { disable_with: "Redirecting..." } %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-outline-primary mx-2', type: 'button', data: { disable_with: "Redirecting..." } %>
            </li>
          <%end%>
        <%end%>
      </ul>
      
    </div>
  </div>
</nav>